BEGIN;
GRANT CONNECT ON DATABASE :DB_NAME TO :DB_OWNER;
GRANT CONNECT ON DATABASE :DB_NAME TO :DB_AUTHENTICATOR;
GRANT ALL ON DATABASE :DB_NAME TO :DB_OWNER;
ALTER SCHEMA public OWNER TO :DB_OWNER;

-- Some extensions require superuser privileges, so we create them before migration time.
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
COMMIT;
